#!/usr/bin/env bash

xhost local:
[ ! -d $HOME/irpf-2017-shared ] && mkdir $HOME/irpf-2017-shared
if [ "$(docker ps -a | grep irpf-2020 | wc -l)" == "1" ]; then
    docker start irpf-2020
else
    docker build -f Dockerfile-2020 -t eszanon/dockerized-irpf-2020 .
    docker run -it -e DISPLAY=$DISPLAY -v /tmp/.X11-unix/:/tmp/.X11-unix/:rw \
        -v /dev/snd:/dev/snd \
        -v $HOME/irpf-2017-shared:/root/shared:rw \
        --name irpf-2020 \
        eszanon/dockerized-irpf-2020 /bin/irpf-2020
fi
